### ISSUE TITLE
(JS-0085) Found some variables redeclared

### ISSUE THREAD

**Issue by stevenruidigao** [CryptoChat-dev/cryptochat#2]
## Description
In JavaScript, it&#x27;s possible to redeclare the same variable name using `var`. This can lead to confusion as to where the variable is actually declared and initialized. Example - The not-preferred way : ```js var a = 3; var a = 10; ``` Example - The preferred way : ```js …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/CryptoChat-dev/cryptochat/issue/JS-0085/occurrences/](https://deepsource.io/gh/CryptoChat-dev/cryptochat/issue/JS-0085/occurrences/)

**Comment by httpjamesm** [comment]
not necessary
