### ISSUE TITLE
Cannot join/create rooms on Edge w/ splash screen

### ISSUE THREAD

**Issue by alexdevz** [CryptoChat-dev/cryptochat#48]

**Comment by stevenruidigao** [comment]
@alexdevz are you using chromium edge or old edge?

**Comment by alexdevz** [comment]
> @alexdevz are you using chromium edge or old edge?

Chromium Edge
~~who uses old edge now~~

**Comment by stevenruidigao** [comment]
@alexdevz it works for me, what version of edge?

**Comment by alexdevz** [comment]
> @alexdevz it works for me, what version of edge?

Latest version.

**Comment by stevenruidigao** [comment]
> > @alexdevz it works for me, what version of edge?
> 
> Latest version.

have you tried clearing cache?

**Comment by alexdevz** [comment]
> > > @alexdevz it works for me, what version of edge?
> 
> > 
> 
> > Latest version.
> 
> 
> 
> have you tried clearing cache?
> 
> 

Yes.

**Comment by stevenruidigao** [comment]
hmmm, well idk

I'm not having any issues on edge.

**Comment by alexdevz** [comment]
![image](https://user-images.githubusercontent.com/38901010/114483410-2366dc80-9bbd-11eb-826d-ad667c4fb614.png)

**Comment by stevenruidigao** [comment]
@alexdevz how did you clear cache

**Comment by alexdevz** [comment]
> @alexdevz how did you clear cache

through edge settings

**Comment by httpjamesm** [comment]
Issue has been inactive for a while. Closing the issue.
